CREATE TABLE "users"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    surname       VARCHAR(255),
    email         VARCHAR(255),
    registered_at TIMESTAMP WITHOUT TIME ZONE,
    password      VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);