CREATE TABLE post
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    body         VARCHAR(255),
    published_at TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE;
