CREATE TABLE comment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value        VARCHAR(255),
    commented_at TIMESTAMP WITHOUT TIME ZONE,
    post_id      BIGINT,
    user_id      BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES "users" (id);